### ISSUE TITLE
função parse_pessoas

### ISSUE THREAD

**Issue by silvadenisson** [abjur/cnc#1]
Quando executo a função parse_pessoas dá um erro):

Error in (1 + i):length(x) : argumento de comprimento zero

Tanto no windows quando macOS.

analisando o código da função encontrei o motivo do erro na subfunção: parse_pessoa_um

mais especificamente na parte que cria o objeto tab_condenacao, na linha:
stringr::str_detect("INFORMA\032\032ES SOBRE A CONDENA\032\032O") %>%

bem, troquei pela string com os acentos normais e funcionou perfeitamente. Talvez fosse bom colocar um if pq ai manteria a ideia original se ainda tiver funcionando para vocês, e facilitava o uso do pacote por quem tá dando esse erro.

Parabéns pelo pacote... que pena que só foi feito depois que fiz minha dissertação com um código que não consegui todas as variáveis, rsrsrss...

Obrigado!

**Comment by jtrecenti** [comment]
Após o refactor de 2020 provavelmente não teremos mais esse problema.
