### ISSUE TITLE
problema quando cnc_pessoas_infos baixa páginas (pessoas) duplicadas

### ISSUE THREAD

**Issue by aassumpcao** [abjur/cnc#2]
Caros,

Comecei a dar uma olhada nos dados do CNC e, além do problema #1, eu encontrei um problema quando baixo as informações pessoais via ```cnc_pessoas_infos()``` para os casos em que há duplicação de páginas pessoais, e.g. ```id_pessoa = 930``` e ```id_pessoa = 6241```.

Meu fix foi *envolver* ```id_pessoas```, de modo que tivéssemos ```unique(id_pessoas)``` nas linhas 136 e 137 do arquivo **cnc.R**.

Grande abraço e obrigado pelo pacote.

André

**Comment by jtrecenti** [comment]
Após o refactor de 2020 provavelmente não teremos mais esse problema.

A função cnc_tidy() ainda está em processo de atualização.
