### ISSUE TITLE
erro função parse_pessoas(arqs)

### ISSUE THREAD

**Issue by lucaseosilva** [abjur/cnc#3]
a função está apresentando problemas tanto no pacote instalado via devtools, como também quando baixo o diretório do github.

como relatado na issue #1 , a questão ainda persiste. quando realizado a alteração proposta, aparece a seguinte mensagem de erro: 

Error in eval_tidy(args[[j]], mask) : objeto 'arqs' não encontrado
 
além disso, aparecem muitas mensagens de alerta devido à defasagem de alguns pacotes. não sei até ponto isso pode estar influenciando.

de qualquer forma, acredito que seria bem vinda uma atualização do pacote.
e, claro, assim como afirmou os demais colegas, agradecemos a contribuição. o pacote auxilia, e muito, toda a comunidade.

**Comment by jtrecenti** [comment]
Olá Lucas, muito obrigado pela issue. O pacote não está em desenvolvimento atualmente. Quando voltar, podemos atacar esse problema.

É bem provável que os parsers não funcionem por conta das atualizações no tidyverse. Talvez o ideal seja construir novas versões dos parsers, utilizando os novos padrões dos pacotes.

**Comment by jtrecenti** [comment]
Após o refactor de 2020 provavelmente não teremos mais esse problema.

A função cnc_tidy() ainda está em processo de atualização.
